#!/usr/bin/env bash

script_dir=$(dirname "$0")
source_dir=$(dirname "$script_dir")

if [ $(id -u) -ne 0 ]; then
  >&2 echo "$0: not running as root"
  exit 1
fi

case "$1" in
  b*)
    target=$2
    nix flake update
    nixos-rebuild switch --flake "$source_dir"#"$target"
    ;;

  r*)
    target=$2
    nix flake lock
    nixos-rebuild switch --flake "$source_dir"#"$target"
    ;;

  u*)
    nix flake update
    ;;

  h*)
    >&2 echo "usage: $0 [bump|rebuild|update|help]"
    ;;
esac
