#!/usr/bin/env bash

script_dir=$(dirname $0)
source_dir=$(dirname $script_dir)

if [ $(id -u) -ne 0 ]; then
  >&2 echo "rebuild-nix: not running as root"
  exit 1
fi

cp -vr $source_dir/machines /etc/nixos/
cp -vr $source_dir/packages /etc/nixos/
cp -vr $source_dir/roles /etc/nixos/
cp -vr $source_dir/users /etc/nixos/
nixos-rebuild -j 4 switch
