#!/usr/bin/env bash

script_dir=$(dirname "$0")
source_dir=$(dirname "$script_dir")
target=$1

if [ $(id -u) -ne 0 ]; then
  >&2 echo "$0: not running as root"
  exit 1
fi

nixos-rebuild switch --flake "$source_dir"#"$target"
